language: python
os:
    - linux
    ## - osx
python:
    - 2.7

matrix:
    allow_failures:
        - python: 3.3
addons:
    apt:
        packages:
            - liblzo2-dev
before_install:
    # Use miniconda for dependencies, pip is too slow -- https://gist.github.com/zonca/9958333
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
  # add for profile
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install: 
    - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION Cython numpy nose
    - source activate testenv
    - python setup.py build_ext --inplace
    - python setup.py install
# add for profile
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - pip install nose-cprof
    - pip install properform

script: 
    - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_bx-python_c7fa844ff2_3
    - python -m properform Push 47.88.50.110:15554 asdf_bx-python_c7fa844ff2_3 ./profile_bx-python_c7fa844ff2_3
#2017-08-10 18:11:15 modified at 0#2017-08-10 18:11:21 modified at 1#2017-08-10 18:11:27 modified at 2#2017-08-10 18:11:33 modified at 3